name: macOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pymupdf python-docx

      # Step 4: Build the executable with PyInstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed \
            --add-data "gift_stamp.png:." \
            --add-data "igb.png:." \
            --add-data "bubble.png:." \
            --add-data "show.png:." \
            --add-data "pic.png:." \
            --add-data "priority.png:." \
            --add-data "short.png:." \
            --add-data "HJLM.png:." \
            --add-data "fed.png:." \
            pdf_processor.py

      # Step 5: Upload the build artifact using the updated version
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: dist/
